functionality:
  name: combine_columns
  namespace: template
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      multiple: true
      required: true
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:23.09-py3
    setup:
      - type: apt
        packages: [ r-base ]
  - type: nextflow
    directives:
      label: [gpu]