functionality:
  name: combine_columns
  namespace: template
  arguments:
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      multiple: true
      required: true
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      required: true
      direction: output
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: eddelbuettel/r2u:22.04
    setup:
      - type: docker
        run: |
          curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
          && curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
          sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
          sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
      - type: apt
        packages: nvidia-container-toolkit
  - type: nextflow
    directives:
      label: [gpu]